name: Build and release for Windows

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          gcc

    - name: Install libsodium
      run: |
        git clone https://github.com/input-output-hk/libsodium
        cd libsodium
        git checkout 66f017f1
        ./autogen.sh
        ./configure --prefix="$(pwd)/libsodium-win64"
        make
        make install
